title: ColDog Studios | Docs
description: Various documentation for ColDog Studios projects.
theme: just-the-docs

url: https://docs.coldogstudios.com

aux_links:
    Template Repository: https://github.com/ColDog-Studios/docs
