name: CI

on:
    push:
        branches: ["main"]
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Ruby
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: "3.3"
                  bundler-cache: true
                  cache-version: 0
            - name: Unfreeze Bundler Config
              run: bundle config set frozen false
            - name: Build with Jekyll
              run: |
                  bundle install
                  bundle exec jekyll build
